// simpcl.c was generated by BuildTuxedo on 12/01/16 @ 22:05:02  ***** DO NOT EDIT *****

#include <tmenv.h>
#include <xa.h>
#include <atmi.h>

#include "include_me.h"

#if defined(__cplusplus)
extern "C" {
#endif
_TMDLLIMPORT 
extern struct xa_switch_t tmnull_switch;
#if defined(__cplusplus)
}
#endif

