// ChangeMe.c was generated by BuildTuxedo on 12/01/16 @ 22:06:17  ***** DO NOT EDIT *****

#include <tmenv.h>
#include <xa.h>
#include <atmi.h>

#include "include_me.h"

main(){
	tuxputenv("WSNADDR=//120.26.79.234:5555");
	if (tpinit((TPINIT *) NULL) == -1) {
		(void) fprintf(stderr, "Tpinit failed\n");
		exit(1);
	}
}